const PRODUCTS_DATA = [
  {
    "id": "prod-001",
    "title": "Vestido Midi Linho Terracota #1",
    "category": "Vestidos",
    "price": 10.0,
    "size": "P",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_130831177.jpg",
    "originalImage": "Brechó/IMG_20260731_130831177.jpg"
  },
  {
    "id": "prod-002",
    "title": "Calça Pantacourt Terracota #2",
    "category": "Calças",
    "price": 12.0,
    "size": "M",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_130948639.jpg",
    "originalImage": "Brechó/IMG_20260731_130948639.jpg"
  },
  {
    "id": "prod-003",
    "title": "Saia Evasê Estampa Botânica #3",
    "category": "Saias",
    "price": 15.0,
    "size": "G",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_134458111_HDR.jpg",
    "originalImage": "Brechó/IMG_20260731_134458111_HDR.jpg"
  },
  {
    "id": "prod-004",
    "title": "Blazer Alfaiataria Retrô #4",
    "category": "Casacos",
    "price": 18.0,
    "size": "GG",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_134509870_HDR.jpg",
    "originalImage": "Brechó/IMG_20260731_134509870_HDR.jpg"
  },
  {
    "id": "prod-005",
    "title": "Colar Artesanal Pedras Naturais #5",
    "category": "Acessórios",
    "price": 20.0,
    "size": "Único",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_134636337_HDR.jpg",
    "originalImage": "Brechó/IMG_20260731_134636337_HDR.jpg"
  },
  {
    "id": "prod-006",
    "title": "Top Estampa Étnica Boemia #6",
    "category": "Blusas",
    "price": 22.0,
    "size": "36",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_134840359.jpg",
    "originalImage": "Brechó/IMG_20260731_134840359.jpg"
  },
  {
    "id": "prod-007",
    "title": "Vestido Evasê Estampa Étnica #7",
    "category": "Vestidos",
    "price": 25.0,
    "size": "38",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_134945448.jpg",
    "originalImage": "Brechó/IMG_20260731_134945448.jpg"
  },
  {
    "id": "prod-008",
    "title": "Calça Pantacourt Terracota #8",
    "category": "Calças",
    "price": 28.0,
    "size": "40",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_135412932_HDR.jpg",
    "originalImage": "Brechó/IMG_20260731_135412932_HDR.jpg"
  },
  {
    "id": "prod-009",
    "title": "Saia Evasê Estampa Botânica #9",
    "category": "Saias",
    "price": 30.0,
    "size": "42",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_135457985.jpg",
    "originalImage": "Brechó/IMG_20260731_135457985.jpg"
  },
  {
    "id": "prod-010",
    "title": "Blazer Alfaiataria Retrô #10",
    "category": "Casacos",
    "price": 32.0,
    "size": "44",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_135515832_HDR.jpg",
    "originalImage": "Brechó/IMG_20260731_135515832_HDR.jpg"
  },
  {
    "id": "prod-011",
    "title": "Colar Artesanal Pedras Naturais #11",
    "category": "Acessórios",
    "price": 35.0,
    "size": "PP",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_140536238.jpg",
    "originalImage": "Brechó/IMG_20260731_140536238.jpg"
  },
  {
    "id": "prod-012",
    "title": "Blusa Ciganinha de Algodão Terroso #12",
    "category": "Blusas",
    "price": 38.0,
    "size": "P",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_140546499.jpg",
    "originalImage": "Brechó/IMG_20260731_140546499.jpg"
  },
  {
    "id": "prod-013",
    "title": "Vestido Midi Verde Oliva #13",
    "category": "Vestidos",
    "price": 40.0,
    "size": "M",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_140653663.jpg",
    "originalImage": "Brechó/IMG_20260731_140653663.jpg"
  },
  {
    "id": "prod-014",
    "title": "Calça Pantacourt Terracota #14",
    "category": "Calças",
    "price": 42.0,
    "size": "G",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_140820778.jpg",
    "originalImage": "Brechó/IMG_20260731_140820778.jpg"
  },
  {
    "id": "prod-015",
    "title": "Saia Evasê Estampa Botânica #15",
    "category": "Saias",
    "price": 45.0,
    "size": "GG",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_140839839.jpg",
    "originalImage": "Brechó/IMG_20260731_140839839.jpg"
  },
  {
    "id": "prod-016",
    "title": "Blazer Alfaiataria Retrô #16",
    "category": "Casacos",
    "price": 48.0,
    "size": "Único",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_140920222.jpg",
    "originalImage": "Brechó/IMG_20260731_140920222.jpg"
  },
  {
    "id": "prod-017",
    "title": "Colar Artesanal Pedras Naturais #17",
    "category": "Acessórios",
    "price": 50.0,
    "size": "36",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_140951917.jpg",
    "originalImage": "Brechó/IMG_20260731_140951917.jpg"
  },
  {
    "id": "prod-018",
    "title": "Top Estampa Étnica Boemia #18",
    "category": "Blusas",
    "price": 5.0,
    "size": "38",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_141101467.jpg",
    "originalImage": "Brechó/IMG_20260731_141101467.jpg"
  },
  {
    "id": "prod-019",
    "title": "Vestido Midi Linho Terracota #19",
    "category": "Vestidos",
    "price": 10.0,
    "size": "40",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_141202473.jpg",
    "originalImage": "Brechó/IMG_20260731_141202473.jpg"
  },
  {
    "id": "prod-020",
    "title": "Calça Pantacourt Terracota #20",
    "category": "Calças",
    "price": 12.0,
    "size": "42",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_141445201.jpg",
    "originalImage": "Brechó/IMG_20260731_141445201.jpg"
  },
  {
    "id": "prod-021",
    "title": "Saia Evasê Estampa Botânica #21",
    "category": "Saias",
    "price": 15.0,
    "size": "44",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_141620466.jpg",
    "originalImage": "Brechó/IMG_20260731_141620466.jpg"
  },
  {
    "id": "prod-022",
    "title": "Blazer Alfaiataria Retrô #22",
    "category": "Casacos",
    "price": 18.0,
    "size": "PP",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_141738737.jpg",
    "originalImage": "Brechó/IMG_20260731_141738737.jpg"
  },
  {
    "id": "prod-023",
    "title": "Colar Artesanal Pedras Naturais #23",
    "category": "Acessórios",
    "price": 20.0,
    "size": "P",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_142000667.jpg",
    "originalImage": "Brechó/IMG_20260731_142000667.jpg"
  },
  {
    "id": "prod-024",
    "title": "Blusa Ciganinha de Algodão Terroso #24",
    "category": "Blusas",
    "price": 22.0,
    "size": "M",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_142018294.jpg",
    "originalImage": "Brechó/IMG_20260731_142018294.jpg"
  },
  {
    "id": "prod-025",
    "title": "Vestido Evasê Estampa Étnica #25",
    "category": "Vestidos",
    "price": 25.0,
    "size": "G",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_142114649.jpg",
    "originalImage": "Brechó/IMG_20260731_142114649.jpg"
  },
  {
    "id": "prod-026",
    "title": "Calça Pantacourt Terracota #26",
    "category": "Calças",
    "price": 28.0,
    "size": "GG",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_142125548.jpg",
    "originalImage": "Brechó/IMG_20260731_142125548.jpg"
  },
  {
    "id": "prod-027",
    "title": "Saia Evasê Estampa Botânica #27",
    "category": "Saias",
    "price": 30.0,
    "size": "Único",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_142218733.jpg",
    "originalImage": "Brechó/IMG_20260731_142218733.jpg"
  },
  {
    "id": "prod-028",
    "title": "Blazer Alfaiataria Retrô #28",
    "category": "Casacos",
    "price": 32.0,
    "size": "36",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_142323907.jpg",
    "originalImage": "Brechó/IMG_20260731_142323907.jpg"
  },
  {
    "id": "prod-029",
    "title": "Colar Artesanal Pedras Naturais #29",
    "category": "Acessórios",
    "price": 35.0,
    "size": "38",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_142332829.jpg",
    "originalImage": "Brechó/IMG_20260731_142332829.jpg"
  },
  {
    "id": "prod-030",
    "title": "Top Estampa Étnica Boemia #30",
    "category": "Blusas",
    "price": 38.0,
    "size": "40",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_142419236.jpg",
    "originalImage": "Brechó/IMG_20260731_142419236.jpg"
  },
  {
    "id": "prod-031",
    "title": "Vestido Midi Verde Oliva #31",
    "category": "Vestidos",
    "price": 40.0,
    "size": "42",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_142529142.jpg",
    "originalImage": "Brechó/IMG_20260731_142529142.jpg"
  },
  {
    "id": "prod-032",
    "title": "Calça Pantacourt Terracota #32",
    "category": "Calças",
    "price": 42.0,
    "size": "44",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_142556125.jpg",
    "originalImage": "Brechó/IMG_20260731_142556125.jpg"
  },
  {
    "id": "prod-033",
    "title": "Saia Evasê Estampa Botânica #33",
    "category": "Saias",
    "price": 45.0,
    "size": "PP",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_142716995.jpg",
    "originalImage": "Brechó/IMG_20260731_142716995.jpg"
  },
  {
    "id": "prod-034",
    "title": "Blazer Alfaiataria Retrô #34",
    "category": "Casacos",
    "price": 48.0,
    "size": "P",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_143041902.jpg",
    "originalImage": "Brechó/IMG_20260731_143041902.jpg"
  },
  {
    "id": "prod-035",
    "title": "Colar Artesanal Pedras Naturais #35",
    "category": "Acessórios",
    "price": 50.0,
    "size": "M",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_143226303.jpg",
    "originalImage": "Brechó/IMG_20260731_143226303.jpg"
  },
  {
    "id": "prod-036",
    "title": "Blusa Ciganinha de Algodão Terroso #36",
    "category": "Blusas",
    "price": 5.0,
    "size": "G",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_143343642.jpg",
    "originalImage": "Brechó/IMG_20260731_143343642.jpg"
  },
  {
    "id": "prod-037",
    "title": "Vestido Midi Linho Terracota #37",
    "category": "Vestidos",
    "price": 10.0,
    "size": "GG",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_143454665.jpg",
    "originalImage": "Brechó/IMG_20260731_143454665.jpg"
  },
  {
    "id": "prod-038",
    "title": "Calça Pantacourt Terracota #38",
    "category": "Calças",
    "price": 12.0,
    "size": "Único",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_143534707.jpg",
    "originalImage": "Brechó/IMG_20260731_143534707.jpg"
  },
  {
    "id": "prod-039",
    "title": "Saia Evasê Estampa Botânica #39",
    "category": "Saias",
    "price": 15.0,
    "size": "36",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_143542179.jpg",
    "originalImage": "Brechó/IMG_20260731_143542179.jpg"
  },
  {
    "id": "prod-040",
    "title": "Blazer Alfaiataria Retrô #40",
    "category": "Casacos",
    "price": 18.0,
    "size": "38",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_143613728.jpg",
    "originalImage": "Brechó/IMG_20260731_143613728.jpg"
  },
  {
    "id": "prod-041",
    "title": "Colar Artesanal Pedras Naturais #41",
    "category": "Acessórios",
    "price": 20.0,
    "size": "40",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_143714203.jpg",
    "originalImage": "Brechó/IMG_20260731_143714203.jpg"
  },
  {
    "id": "prod-042",
    "title": "Top Estampa Étnica Boemia #42",
    "category": "Blusas",
    "price": 22.0,
    "size": "42",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_143918686.jpg",
    "originalImage": "Brechó/IMG_20260731_143918686.jpg"
  },
  {
    "id": "prod-043",
    "title": "Vestido Evasê Estampa Étnica #43",
    "category": "Vestidos",
    "price": 25.0,
    "size": "44",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_144014362.jpg",
    "originalImage": "Brechó/IMG_20260731_144014362.jpg"
  },
  {
    "id": "prod-044",
    "title": "Calça Pantacourt Terracota #44",
    "category": "Calças",
    "price": 28.0,
    "size": "PP",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_144028828.jpg",
    "originalImage": "Brechó/IMG_20260731_144028828.jpg"
  },
  {
    "id": "prod-045",
    "title": "Saia Evasê Estampa Botânica #45",
    "category": "Saias",
    "price": 30.0,
    "size": "P",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_144133512.jpg",
    "originalImage": "Brechó/IMG_20260731_144133512.jpg"
  },
  {
    "id": "prod-046",
    "title": "Blazer Alfaiataria Retrô #46",
    "category": "Casacos",
    "price": 32.0,
    "size": "M",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_144428292.jpg",
    "originalImage": "Brechó/IMG_20260731_144428292.jpg"
  },
  {
    "id": "prod-047",
    "title": "Colar Artesanal Pedras Naturais #47",
    "category": "Acessórios",
    "price": 35.0,
    "size": "G",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_144440982.jpg",
    "originalImage": "Brechó/IMG_20260731_144440982.jpg"
  },
  {
    "id": "prod-048",
    "title": "Blusa Ciganinha de Algodão Terroso #48",
    "category": "Blusas",
    "price": 38.0,
    "size": "GG",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_144543012.jpg",
    "originalImage": "Brechó/IMG_20260731_144543012.jpg"
  },
  {
    "id": "prod-049",
    "title": "Vestido Midi Verde Oliva #49",
    "category": "Vestidos",
    "price": 40.0,
    "size": "Único",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_144557280.jpg",
    "originalImage": "Brechó/IMG_20260731_144557280.jpg"
  },
  {
    "id": "prod-050",
    "title": "Calça Pantacourt Terracota #50",
    "category": "Calças",
    "price": 42.0,
    "size": "36",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_144639577.jpg",
    "originalImage": "Brechó/IMG_20260731_144639577.jpg"
  },
  {
    "id": "prod-051",
    "title": "Saia Evasê Estampa Botânica #51",
    "category": "Saias",
    "price": 45.0,
    "size": "38",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_144653852.jpg",
    "originalImage": "Brechó/IMG_20260731_144653852.jpg"
  },
  {
    "id": "prod-052",
    "title": "Blazer Alfaiataria Retrô #52",
    "category": "Casacos",
    "price": 48.0,
    "size": "40",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_144737554.jpg",
    "originalImage": "Brechó/IMG_20260731_144737554.jpg"
  },
  {
    "id": "prod-053",
    "title": "Colar Artesanal Pedras Naturais #53",
    "category": "Acessórios",
    "price": 50.0,
    "size": "42",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_144746572.jpg",
    "originalImage": "Brechó/IMG_20260731_144746572.jpg"
  },
  {
    "id": "prod-054",
    "title": "Top Estampa Étnica Boemia #54",
    "category": "Blusas",
    "price": 5.0,
    "size": "44",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_145017636.jpg",
    "originalImage": "Brechó/IMG_20260731_145017636.jpg"
  },
  {
    "id": "prod-055",
    "title": "Vestido Midi Linho Terracota #55",
    "category": "Vestidos",
    "price": 10.0,
    "size": "PP",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_145113531.jpg",
    "originalImage": "Brechó/IMG_20260731_145113531.jpg"
  },
  {
    "id": "prod-056",
    "title": "Calça Pantacourt Terracota #56",
    "category": "Calças",
    "price": 12.0,
    "size": "P",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_145216792.jpg",
    "originalImage": "Brechó/IMG_20260731_145216792.jpg"
  },
  {
    "id": "prod-057",
    "title": "Saia Evasê Estampa Botânica #57",
    "category": "Saias",
    "price": 15.0,
    "size": "M",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_145231852.jpg",
    "originalImage": "Brechó/IMG_20260731_145231852.jpg"
  },
  {
    "id": "prod-058",
    "title": "Blazer Alfaiataria Retrô #58",
    "category": "Casacos",
    "price": 18.0,
    "size": "G",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_145355098.jpg",
    "originalImage": "Brechó/IMG_20260731_145355098.jpg"
  },
  {
    "id": "prod-059",
    "title": "Colar Artesanal Pedras Naturais #59",
    "category": "Acessórios",
    "price": 20.0,
    "size": "GG",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_145404839.jpg",
    "originalImage": "Brechó/IMG_20260731_145404839.jpg"
  },
  {
    "id": "prod-060",
    "title": "Blusa Ciganinha de Algodão Terroso #60",
    "category": "Blusas",
    "price": 22.0,
    "size": "Único",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_145442902.jpg",
    "originalImage": "Brechó/IMG_20260731_145442902.jpg"
  },
  {
    "id": "prod-061",
    "title": "Vestido Evasê Estampa Étnica #61",
    "category": "Vestidos",
    "price": 25.0,
    "size": "36",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_145500853.jpg",
    "originalImage": "Brechó/IMG_20260731_145500853.jpg"
  },
  {
    "id": "prod-062",
    "title": "Calça Pantacourt Terracota #62",
    "category": "Calças",
    "price": 28.0,
    "size": "38",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_145555266.jpg",
    "originalImage": "Brechó/IMG_20260731_145555266.jpg"
  },
  {
    "id": "prod-063",
    "title": "Saia Evasê Estampa Botânica #63",
    "category": "Saias",
    "price": 30.0,
    "size": "40",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_145610834.jpg",
    "originalImage": "Brechó/IMG_20260731_145610834.jpg"
  },
  {
    "id": "prod-064",
    "title": "Blazer Alfaiataria Retrô #64",
    "category": "Casacos",
    "price": 32.0,
    "size": "42",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_145838643.jpg",
    "originalImage": "Brechó/IMG_20260731_145838643.jpg"
  },
  {
    "id": "prod-065",
    "title": "Colar Artesanal Pedras Naturais #65",
    "category": "Acessórios",
    "price": 35.0,
    "size": "44",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_145857286.jpg",
    "originalImage": "Brechó/IMG_20260731_145857286.jpg"
  },
  {
    "id": "prod-066",
    "title": "Top Estampa Étnica Boemia #66",
    "category": "Blusas",
    "price": 38.0,
    "size": "PP",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_150138881.jpg",
    "originalImage": "Brechó/IMG_20260731_150138881.jpg"
  },
  {
    "id": "prod-067",
    "title": "Vestido Midi Verde Oliva #67",
    "category": "Vestidos",
    "price": 40.0,
    "size": "P",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_150158739.jpg",
    "originalImage": "Brechó/IMG_20260731_150158739.jpg"
  },
  {
    "id": "prod-068",
    "title": "Calça Pantacourt Terracota #68",
    "category": "Calças",
    "price": 42.0,
    "size": "M",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_150333497.jpg",
    "originalImage": "Brechó/IMG_20260731_150333497.jpg"
  },
  {
    "id": "prod-069",
    "title": "Saia Evasê Estampa Botânica #69",
    "category": "Saias",
    "price": 45.0,
    "size": "G",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_150351099.jpg",
    "originalImage": "Brechó/IMG_20260731_150351099.jpg"
  },
  {
    "id": "prod-070",
    "title": "Blazer Alfaiataria Retrô #70",
    "category": "Casacos",
    "price": 48.0,
    "size": "GG",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_150447309.jpg",
    "originalImage": "Brechó/IMG_20260731_150447309.jpg"
  },
  {
    "id": "prod-071",
    "title": "Colar Artesanal Pedras Naturais #71",
    "category": "Acessórios",
    "price": 50.0,
    "size": "Único",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_150500725.jpg",
    "originalImage": "Brechó/IMG_20260731_150500725.jpg"
  },
  {
    "id": "prod-072",
    "title": "Blusa Ciganinha de Algodão Terroso #72",
    "category": "Blusas",
    "price": 5.0,
    "size": "36",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_150614186.jpg",
    "originalImage": "Brechó/IMG_20260731_150614186.jpg"
  },
  {
    "id": "prod-073",
    "title": "Vestido Midi Linho Terracota #73",
    "category": "Vestidos",
    "price": 10.0,
    "size": "38",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_150625800.jpg",
    "originalImage": "Brechó/IMG_20260731_150625800.jpg"
  },
  {
    "id": "prod-074",
    "title": "Calça Pantacourt Terracota #74",
    "category": "Calças",
    "price": 12.0,
    "size": "40",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_150724988.jpg",
    "originalImage": "Brechó/IMG_20260731_150724988.jpg"
  },
  {
    "id": "prod-075",
    "title": "Saia Evasê Estampa Botânica #75",
    "category": "Saias",
    "price": 15.0,
    "size": "42",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_150810462.jpg",
    "originalImage": "Brechó/IMG_20260731_150810462.jpg"
  },
  {
    "id": "prod-076",
    "title": "Blazer Alfaiataria Retrô #76",
    "category": "Casacos",
    "price": 18.0,
    "size": "44",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_151008515.jpg",
    "originalImage": "Brechó/IMG_20260731_151008515.jpg"
  },
  {
    "id": "prod-077",
    "title": "Colar Artesanal Pedras Naturais #77",
    "category": "Acessórios",
    "price": 20.0,
    "size": "PP",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_151038124.jpg",
    "originalImage": "Brechó/IMG_20260731_151038124.jpg"
  },
  {
    "id": "prod-078",
    "title": "Top Estampa Étnica Boemia #78",
    "category": "Blusas",
    "price": 22.0,
    "size": "P",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_151201005.jpg",
    "originalImage": "Brechó/IMG_20260731_151201005.jpg"
  },
  {
    "id": "prod-079",
    "title": "Vestido Evasê Estampa Étnica #79",
    "category": "Vestidos",
    "price": 25.0,
    "size": "M",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_151220254.jpg",
    "originalImage": "Brechó/IMG_20260731_151220254.jpg"
  },
  {
    "id": "prod-080",
    "title": "Calça Pantacourt Terracota #80",
    "category": "Calças",
    "price": 28.0,
    "size": "G",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_151332662.jpg",
    "originalImage": "Brechó/IMG_20260731_151332662.jpg"
  },
  {
    "id": "prod-081",
    "title": "Saia Evasê Estampa Botânica #81",
    "category": "Saias",
    "price": 30.0,
    "size": "GG",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_151350055.jpg",
    "originalImage": "Brechó/IMG_20260731_151350055.jpg"
  },
  {
    "id": "prod-082",
    "title": "Blazer Alfaiataria Retrô #82",
    "category": "Casacos",
    "price": 32.0,
    "size": "Único",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_151834179.jpg",
    "originalImage": "Brechó/IMG_20260731_151834179.jpg"
  },
  {
    "id": "prod-083",
    "title": "Colar Artesanal Pedras Naturais #83",
    "category": "Acessórios",
    "price": 35.0,
    "size": "36",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_151943802.jpg",
    "originalImage": "Brechó/IMG_20260731_151943802.jpg"
  },
  {
    "id": "prod-084",
    "title": "Blusa Ciganinha de Algodão Terroso #84",
    "category": "Blusas",
    "price": 38.0,
    "size": "38",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_152138816.jpg",
    "originalImage": "Brechó/IMG_20260731_152138816.jpg"
  },
  {
    "id": "prod-085",
    "title": "Vestido Midi Verde Oliva #85",
    "category": "Vestidos",
    "price": 40.0,
    "size": "40",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_152218842.jpg",
    "originalImage": "Brechó/IMG_20260731_152218842.jpg"
  },
  {
    "id": "prod-086",
    "title": "Calça Pantacourt Terracota #86",
    "category": "Calças",
    "price": 42.0,
    "size": "42",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_152547775.jpg",
    "originalImage": "Brechó/IMG_20260731_152547775.jpg"
  },
  {
    "id": "prod-087",
    "title": "Saia Evasê Estampa Botânica #87",
    "category": "Saias",
    "price": 45.0,
    "size": "44",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_152621820.jpg",
    "originalImage": "Brechó/IMG_20260731_152621820.jpg"
  },
  {
    "id": "prod-088",
    "title": "Blazer Alfaiataria Retrô #88",
    "category": "Casacos",
    "price": 48.0,
    "size": "PP",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_152803333.jpg",
    "originalImage": "Brechó/IMG_20260731_152803333.jpg"
  },
  {
    "id": "prod-089",
    "title": "Colar Artesanal Pedras Naturais #89",
    "category": "Acessórios",
    "price": 50.0,
    "size": "P",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_152833818.jpg",
    "originalImage": "Brechó/IMG_20260731_152833818.jpg"
  },
  {
    "id": "prod-090",
    "title": "Top Estampa Étnica Boemia #90",
    "category": "Blusas",
    "price": 5.0,
    "size": "M",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_152947289.jpg",
    "originalImage": "Brechó/IMG_20260731_152947289.jpg"
  },
  {
    "id": "prod-091",
    "title": "Vestido Midi Linho Terracota #91",
    "category": "Vestidos",
    "price": 10.0,
    "size": "G",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_152958519.jpg",
    "originalImage": "Brechó/IMG_20260731_152958519.jpg"
  },
  {
    "id": "prod-092",
    "title": "Calça Pantacourt Terracota #92",
    "category": "Calças",
    "price": 12.0,
    "size": "GG",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_153107764.jpg",
    "originalImage": "Brechó/IMG_20260731_153107764.jpg"
  },
  {
    "id": "prod-093",
    "title": "Saia Evasê Estampa Botânica #93",
    "category": "Saias",
    "price": 15.0,
    "size": "Único",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_153122364.jpg",
    "originalImage": "Brechó/IMG_20260731_153122364.jpg"
  },
  {
    "id": "prod-094",
    "title": "Blazer Alfaiataria Retrô #94",
    "category": "Casacos",
    "price": 18.0,
    "size": "36",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_153321166.jpg",
    "originalImage": "Brechó/IMG_20260731_153321166.jpg"
  },
  {
    "id": "prod-095",
    "title": "Colar Artesanal Pedras Naturais #95",
    "category": "Acessórios",
    "price": 20.0,
    "size": "38",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_153350300.jpg",
    "originalImage": "Brechó/IMG_20260731_153350300.jpg"
  },
  {
    "id": "prod-096",
    "title": "Blusa Ciganinha de Algodão Terroso #96",
    "category": "Blusas",
    "price": 22.0,
    "size": "40",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_153502668.jpg",
    "originalImage": "Brechó/IMG_20260731_153502668.jpg"
  },
  {
    "id": "prod-097",
    "title": "Vestido Evasê Estampa Étnica #97",
    "category": "Vestidos",
    "price": 25.0,
    "size": "42",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_153511931.jpg",
    "originalImage": "Brechó/IMG_20260731_153511931.jpg"
  },
  {
    "id": "prod-098",
    "title": "Calça Pantacourt Terracota #98",
    "category": "Calças",
    "price": 28.0,
    "size": "44",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_153557016.jpg",
    "originalImage": "Brechó/IMG_20260731_153557016.jpg"
  },
  {
    "id": "prod-099",
    "title": "Saia Evasê Estampa Botânica #99",
    "category": "Saias",
    "price": 30.0,
    "size": "PP",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_153616190.jpg",
    "originalImage": "Brechó/IMG_20260731_153616190.jpg"
  },
  {
    "id": "prod-100",
    "title": "Blazer Alfaiataria Retrô #100",
    "category": "Casacos",
    "price": 32.0,
    "size": "P",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_153736761.jpg",
    "originalImage": "Brechó/IMG_20260731_153736761.jpg"
  },
  {
    "id": "prod-101",
    "title": "Colar Artesanal Pedras Naturais #101",
    "category": "Acessórios",
    "price": 35.0,
    "size": "M",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_153750854.jpg",
    "originalImage": "Brechó/IMG_20260731_153750854.jpg"
  },
  {
    "id": "prod-102",
    "title": "Top Estampa Étnica Boemia #102",
    "category": "Blusas",
    "price": 38.0,
    "size": "G",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_153916664.jpg",
    "originalImage": "Brechó/IMG_20260731_153916664.jpg"
  },
  {
    "id": "prod-103",
    "title": "Vestido Midi Verde Oliva #103",
    "category": "Vestidos",
    "price": 40.0,
    "size": "GG",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_153934745.jpg",
    "originalImage": "Brechó/IMG_20260731_153934745.jpg"
  },
  {
    "id": "prod-104",
    "title": "Calça Pantacourt Terracota #104",
    "category": "Calças",
    "price": 42.0,
    "size": "Único",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_154033088.jpg",
    "originalImage": "Brechó/IMG_20260731_154033088.jpg"
  },
  {
    "id": "prod-105",
    "title": "Saia Evasê Estampa Botânica #105",
    "category": "Saias",
    "price": 45.0,
    "size": "36",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_154148283.jpg",
    "originalImage": "Brechó/IMG_20260731_154148283.jpg"
  },
  {
    "id": "prod-106",
    "title": "Blazer Alfaiataria Retrô #106",
    "category": "Casacos",
    "price": 48.0,
    "size": "38",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_154215122.jpg",
    "originalImage": "Brechó/IMG_20260731_154215122.jpg"
  },
  {
    "id": "prod-107",
    "title": "Colar Artesanal Pedras Naturais #107",
    "category": "Acessórios",
    "price": 50.0,
    "size": "40",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_154338341.jpg",
    "originalImage": "Brechó/IMG_20260731_154338341.jpg"
  },
  {
    "id": "prod-108",
    "title": "Blusa Ciganinha de Algodão Terroso #108",
    "category": "Blusas",
    "price": 5.0,
    "size": "42",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_154356695.jpg",
    "originalImage": "Brechó/IMG_20260731_154356695.jpg"
  },
  {
    "id": "prod-109",
    "title": "Vestido Midi Linho Terracota #109",
    "category": "Vestidos",
    "price": 10.0,
    "size": "44",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_154520671.jpg",
    "originalImage": "Brechó/IMG_20260731_154520671.jpg"
  },
  {
    "id": "prod-110",
    "title": "Calça Pantacourt Terracota #110",
    "category": "Calças",
    "price": 12.0,
    "size": "PP",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_154536545.jpg",
    "originalImage": "Brechó/IMG_20260731_154536545.jpg"
  },
  {
    "id": "prod-111",
    "title": "Saia Evasê Estampa Botânica #111",
    "category": "Saias",
    "price": 15.0,
    "size": "P",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_154707590_HDR.jpg",
    "originalImage": "Brechó/IMG_20260731_154707590_HDR.jpg"
  },
  {
    "id": "prod-112",
    "title": "Blazer Alfaiataria Retrô #112",
    "category": "Casacos",
    "price": 18.0,
    "size": "M",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_154725878.jpg",
    "originalImage": "Brechó/IMG_20260731_154725878.jpg"
  },
  {
    "id": "prod-113",
    "title": "Colar Artesanal Pedras Naturais #113",
    "category": "Acessórios",
    "price": 20.0,
    "size": "G",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_154916305.jpg",
    "originalImage": "Brechó/IMG_20260731_154916305.jpg"
  },
  {
    "id": "prod-114",
    "title": "Top Estampa Étnica Boemia #114",
    "category": "Blusas",
    "price": 22.0,
    "size": "GG",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_154937467.jpg",
    "originalImage": "Brechó/IMG_20260731_154937467.jpg"
  },
  {
    "id": "prod-115",
    "title": "Vestido Evasê Estampa Étnica #115",
    "category": "Vestidos",
    "price": 25.0,
    "size": "Único",
    "badge": "Favorito do Mês",
    "condition": "Garimpo sustentável",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_155606345.jpg",
    "originalImage": "Brechó/IMG_20260731_155606345.jpg"
  },
  {
    "id": "prod-116",
    "title": "Calça Pantacourt Terracota #116",
    "category": "Calças",
    "price": 28.0,
    "size": "36",
    "badge": "Vintage Raiz",
    "condition": "Excelente estado",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_155634588.jpg",
    "originalImage": "Brechó/IMG_20260731_155634588.jpg"
  },
  {
    "id": "prod-117",
    "title": "Saia Evasê Estampa Botânica #117",
    "category": "Saias",
    "price": 30.0,
    "size": "38",
    "badge": null,
    "condition": "Seminovo de acervo",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_155722394.jpg",
    "originalImage": "Brechó/IMG_20260731_155722394.jpg"
  },
  {
    "id": "prod-118",
    "title": "Blazer Alfaiataria Retrô #118",
    "category": "Casacos",
    "price": 32.0,
    "size": "40",
    "badge": null,
    "condition": "Vintage impecável",
    "description": "Tecido leve, toque suave e caimento fluido. Uma preciosidade da moda circular.",
    "image": "images/optimized/IMG_20260731_155745080.jpg",
    "originalImage": "Brechó/IMG_20260731_155745080.jpg"
  },
  {
    "id": "prod-119",
    "title": "Colar Artesanal Pedras Naturais #119",
    "category": "Acessórios",
    "price": 35.0,
    "size": "42",
    "badge": null,
    "condition": "Garimpo sustentável",
    "description": "Garimpo artesanal em perfeitas condições, sem marcas de uso. Edição única!",
    "image": "images/optimized/IMG_20260731_155829790.jpg",
    "originalImage": "Brechó/IMG_20260731_155829790.jpg"
  },
  {
    "id": "prod-120",
    "title": "Blusa Ciganinha de Algodão Terroso #120",
    "category": "Blusas",
    "price": 38.0,
    "size": "44",
    "badge": "Garimpo Único",
    "condition": "Excelente estado",
    "description": "Garimpo exclusivo selecionado a dedo para quem ama estilo único e consumo consciente.",
    "image": "images/optimized/IMG_20260731_155840611.jpg",
    "originalImage": "Brechó/IMG_20260731_155840611.jpg"
  },
  {
    "id": "prod-121",
    "title": "Vestido Midi Verde Oliva #121",
    "category": "Vestidos",
    "price": 40.0,
    "size": "PP",
    "badge": "Destaque Boho",
    "condition": "Seminovo de acervo",
    "description": "Peça vintage cheia de história, tecido extremamente confortável e acabamento impecável.",
    "image": "images/optimized/IMG_20260731_155924729.jpg",
    "originalImage": "Brechó/IMG_20260731_155924729.jpg"
  },
  {
    "id": "prod-122",
    "title": "Calça Pantacourt Terracota #122",
    "category": "Calças",
    "price": 42.0,
    "size": "P",
    "badge": "Achadinho",
    "condition": "Vintage impecável",
    "description": "Modelo super coringa e atemporal, perfeito para compor looks boho chic no dia a dia.",
    "image": "images/optimized/IMG_20260731_155938191.jpg",
    "originalImage": "Brechó/IMG_20260731_155938191.jpg"
  }
];
